import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/components/session-provider";
import {Toaster} from "sonner";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Alexandre Dissi - Cloud Mastere Dev C",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
<SessionProvider>
        {children}
    <Toaster richColors position="top-right"  />
</SessionProvider>
      </body>
    </html>
  );
}
